# This value must be set.
SLACK_API_TOKEN: ""

# Set these values for LDAP lookup support. Switch _ENABLED to true.
LDAP_ENABLED: false
LDAP_HOST: ""
LDAP_PORT: ""
LDAP_BASE_DN: ""
LDAP_BASE_PW: ""
LDAP_SEARCH_DN: ""

# Set these values for Roles Management support. Switch _ENABLED to true.
ROLES_ENABLED: false
ROLES_URL: ""
ROLES_USERNAME: ""
ROLES_TOKEN: ""

# Enable piping to the UNIX 'host' command (with validation)
HOST_ENABLED: false

# An Easter Egg command. Prints the number of minutes of "productivity" left
# until 5:00pm.
VISIONEERS_ENABLED: false

# If true, requires separate github.yml file
GITHUB_ENABLED: false

#Devboard Data
DEVBOARD_ENABLED: false
DEVBOARD_URL: ""
DEVBOARD_API_USER: ""
DEVBOARD_API_SECRET: ""
