SYSAID_ACCOUNT: ""
SYSAID_USER: ""
SYSAID_PASSWORD: ""
SYSAID_URI: "https://your.sysaid.server/services/SysaidApiService?wsdl"

LDAP_HOST: ""
LDAP_PORT: ""
LDAP_BASE_DN: ""
LDAP_BASE_PW: ""
LDAP_SEARCH_DN: ""

SLACK_API_TOKEN: ""

ROLES_URL: ""
ROLES_USERNAME: ""
ROLES_TOKEN: ""
